### ISSUE TITLE
Measuring speed limited by console output speed

### ISSUE THREAD

**Issue by lythro** [Janhouse/tespeed#24]
I set up my Raspberry Pi to periodically measure our bandwidth. Unfortunately, the maximum I was able to measure using your script was about 20 Mbit/s, which is far below what I get when doing the test manually (~60 Mbit/s right now), on speedtest.net. I figured out that this is due to the excessive amout of console output generated: the progress-updates interfere with the download-process. I was able to "tune" your script by simply skipping the "ChunkReport" - Method (inserted an additional 'return' in the first line..). 

(FYI, I'm at  f69ae3e since I get the same errors as in issue #22)

**Comment by Janhouse** [comment]
My guess is that it is limited by the speed of Raspberry. Did you run speedtest.net from raspberry or other device in your network?
