### ISSUE TITLE
How to disable downloading big files

### ISSUE THREAD

**Issue by dtouzeau** [Janhouse/tespeed#31]
When the script perfom tests, it download files multiple times and increase downloaded file size
1.96M, 8.09,17mb,31Mb
Is it possible to limit test only one the first file ( eg 1.96M )  ?

Because all others give about the same results.

**Comment by Janhouse** [comment]
Good idea, implemented. :smiley:

**Comment by dtouzeau** [comment]
How to do ??? 

--max-download-tests 5 ?

**Comment by Janhouse** [comment]
Yup. Or you can use the short param: -ut 5
So, to do maximum 1 download test and 3 upload tests:
```tespeed.py -dt 1 -ut 3```
